# Generated by Django 5.0.4 on 2024-05-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_library', '0002_delete_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartists',
            name='artist_uri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify_library.artists'),
        ),
        migrations.AlterField(
            model_name='usertracks',
            name='track_uri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify_library.tracks'),
        ),
    ]
