# Generated by Django 5.0.4 on 2024-05-09 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_library', '0003_alter_userartists_artist_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='main_artist_uri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify_library.artists'),
        ),
    ]
