# Generated by Django 5.0.4 on 2024-04-30 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('spotify_id', models.CharField(max_length=40)),
                ('access_token', models.CharField(max_length=270)),
                ('refresh_token', models.CharField(max_length=150)),
            ],
        ),
    ]
